[package]
name = "rgbuilder-lang-typescript"
version = "0.4.3"
edition.workspace = true
rust-version.workspace = true
description = "rgBuilder language plugin: typescript"
license = "MIT OR Apache-2.0"

[dependencies]
rgbuilder-plugin-api = { workspace = true }
rgbuilder-registry = { workspace = true }
rgbuilder-plugin-helpers = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-typescript = "0.23"
serde_json = "1"
