[package]
name = "rbuilder-lang-javascript"
version = "0.4.2"
edition.workspace = true
rust-version.workspace = true
description = "rBuilder language plugin: javascript"
license = "MIT OR Apache-2.0"

[dependencies]
rbuilder-plugin-api = { workspace = true }
rbuilder-registry = { workspace = true }
rbuilder-plugin-helpers = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-javascript = "0.25"
rbuilder-semantic = { workspace = true }
serde_json = "1"
