[package]
name = "rbuilder-macros"
version = "0.4.2"
edition.workspace = true
rust-version.workspace = true
description = "Procedural macros for rBuilder language plugins"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
rbuilder-plugin-api = { path = "../crates/rbuilder-plugin-api" }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
