//! Compiled vocabulary matrix + bag-of-tokens accumulator (`vocab-accumulate-v1`).

use rbuilder_error::{Error, Result};
use std::collections::{HashMap, HashSet};
use std::sync::OnceLock;

/// Stable model id for vocab-accumulate indexes.
pub const VOCAB_ACCUMULATE_MODEL_ID: &str = "vocab-accumulate-v1";

/// Native vocabulary embedding width produced by `build.rs`.
pub const VOCAB_NATIVE_DIMENSIONS: usize = 256;

const MAGIC: &[u8; 4] = b"RBVK";
const VERSION: u32 = 1;

static EMBEDDED: OnceLock<&'static [u8]> = OnceLock::new();
static ACCUMULATOR: OnceLock<std::result::Result<TokenSpaceAccumulator, String>> = OnceLock::new();

fn embedded_bytes() -> &'static [u8] {
    EMBEDDED.get_or_init(|| {
        // Generated by build.rs into OUT_DIR; path injected via rustc-env.
        include_bytes!(env!("RBUILDER_VOCAB_MATRIX"))
    })
}

/// Bag-of-tokens accumulator over the compiled int8 vocabulary matrix.
#[derive(Debug, Clone)]
pub struct TokenSpaceAccumulator {
    token_to_idx: HashMap<String, u32>,
    weights: Vec<i8>,
    dimensions: usize,
}

impl TokenSpaceAccumulator {
    /// Parse and validate a vocab matrix blob.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        if bytes.len() < 16 {
            return Err(Error::ConfigError(
                "vocab matrix truncated: header too short".into(),
            ));
        }
        if &bytes[0..4] != MAGIC {
            return Err(Error::ConfigError(
                "vocab matrix: bad magic (expected RBVK)".into(),
            ));
        }
        let version = u32::from_le_bytes(bytes[4..8].try_into().unwrap());
        if version != VERSION {
            return Err(Error::ConfigError(format!(
                "vocab matrix: unsupported version {version}"
            )));
        }
        let n_tokens = u32::from_le_bytes(bytes[8..12].try_into().unwrap()) as usize;
        let dimensions = u32::from_le_bytes(bytes[12..16].try_into().unwrap()) as usize;
        if dimensions == 0 || dimensions % 8 != 0 {
            return Err(Error::ConfigError(format!(
                "vocab matrix: invalid dimensions {dimensions}"
            )));
        }
        if n_tokens == 0 {
            return Err(Error::ConfigError("vocab matrix: empty token table".into()));
        }

        let mut offset = 16usize;
        let mut token_to_idx = HashMap::with_capacity(n_tokens);
        for idx in 0..n_tokens {
            if offset + 2 > bytes.len() {
                return Err(Error::ConfigError(
                    "vocab matrix truncated while reading tokens".into(),
                ));
            }
            let len = u16::from_le_bytes(bytes[offset..offset + 2].try_into().unwrap()) as usize;
            offset += 2;
            if len == 0 || offset + len > bytes.len() {
                return Err(Error::ConfigError(format!(
                    "vocab matrix: invalid token length at index {idx}"
                )));
            }
            let token = std::str::from_utf8(&bytes[offset..offset + len])
                .map_err(|err| Error::ConfigError(format!("vocab matrix utf8: {err}")))?
                .to_ascii_lowercase();
            offset += len;
            token_to_idx.insert(token, idx as u32);
        }

        let weights_len = n_tokens
            .checked_mul(dimensions)
            .ok_or_else(|| Error::ConfigError("vocab matrix: weights overflow".into()))?;
        if offset + weights_len != bytes.len() {
            return Err(Error::ConfigError(format!(
                "vocab matrix: trailing size mismatch (offset={offset}, weights={weights_len}, len={})",
                bytes.len()
            )));
        }

        let mut weights = Vec::with_capacity(weights_len);
        for &b in &bytes[offset..] {
            weights.push(b as i8);
        }

        Ok(Self {
            token_to_idx,
            weights,
            dimensions,
        })
    }

    /// Shared process-wide accumulator over the compiled matrix.
    pub fn global() -> Result<&'static TokenSpaceAccumulator> {
        let slot = ACCUMULATOR.get_or_init(|| {
            Self::from_bytes(embedded_bytes()).map_err(|err| err.to_string())
        });
        match slot {
            Ok(acc) => Ok(acc),
            Err(msg) => Err(Error::ConfigError(msg.clone())),
        }
    }

    /// Vocabulary embedding width.
    pub fn dimensions(&self) -> usize {
        self.dimensions
    }

    /// Number of tokens in the table.
    pub fn token_count(&self) -> usize {
        self.token_to_idx.len()
    }

    /// Accumulate tokens into an L2-normalized dense vector of native width.
    pub fn accumulate_tokens(&self, tokens: &HashSet<String>) -> Vec<f32> {
        let mut dense = vec![0.0f32; self.dimensions];
        let mut matched = 0usize;
        for token in tokens {
            let key = token.to_ascii_lowercase();
            if let Some(&idx) = self.token_to_idx.get(&key) {
                matched += 1;
                let start = idx as usize * self.dimensions;
                let row = &self.weights[start..start + self.dimensions];
                for (d, &w) in row.iter().enumerate() {
                    dense[d] += f32::from(w);
                }
            }
        }
        if matched > 0 {
            l2_normalize(&mut dense);
        }
        dense
    }

    /// Tokenize text (identifier-like) and accumulate, optionally resized to `out_dims`.
    pub fn accumulate_text(&self, text: &str, out_dims: usize) -> Vec<f32> {
        let mut tokens = HashSet::new();
        rbuilder_graph::tokenize_string_into(text, &mut tokens);
        // Also accept simple alphanumeric splits for query strings.
        for piece in text.split(|c: char| !c.is_alphanumeric() && c != '_') {
            if piece.len() >= rbuilder_graph::MIN_TOKEN_LEN {
                tokens.insert(piece.to_ascii_lowercase());
            }
        }
        let native = self.accumulate_tokens(&tokens);
        resize_dense(&native, out_dims)
    }
}

fn l2_normalize(vec: &mut [f32]) {
    let sum_sq: f32 = vec.iter().map(|x| x * x).sum();
    if sum_sq > 0.0 {
        let norm = sum_sq.sqrt();
        for v in vec.iter_mut() {
            *v /= norm;
        }
    }
}

fn resize_dense(native: &[f32], out_dims: usize) -> Vec<f32> {
    if out_dims == native.len() {
        return native.to_vec();
    }
    let mut out = vec![0.0f32; out_dims];
    let copy = native.len().min(out_dims);
    out[..copy].copy_from_slice(&native[..copy]);
    if copy > 0 {
        l2_normalize(&mut out);
    }
    out
}

/// Embedder backed by [`TokenSpaceAccumulator`].
#[derive(Debug, Clone)]
pub struct VocabAccumulateEmbedder {
    dimensions: usize,
}

impl VocabAccumulateEmbedder {
    /// Create an embedder that outputs `dimensions` floats (prefer 256).
    pub fn new(dimensions: usize) -> Result<Self> {
        if dimensions == 0 || dimensions % 8 != 0 {
            return Err(Error::ConfigError(
                "vocab embedder dimensions must be a positive multiple of 8".into(),
            ));
        }
        // Ensure matrix loads at construction time.
        let _ = TokenSpaceAccumulator::global()?;
        Ok(Self { dimensions })
    }
}

impl crate::semantic_embedder::SemanticEmbedder for VocabAccumulateEmbedder {
    fn model_id(&self) -> &str {
        VOCAB_ACCUMULATE_MODEL_ID
    }

    fn dimensions(&self) -> usize {
        self.dimensions
    }

    fn embed(&self, text: &str) -> Result<Vec<f32>> {
        let acc = TokenSpaceAccumulator::global()?;
        Ok(acc.accumulate_text(text, self.dimensions))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::semantic_embedder::SemanticEmbedder;
    use crate::semantic_search::quantize_binary;

    #[test]
    fn embedded_matrix_loads() {
        let acc = TokenSpaceAccumulator::global().expect("load vocab");
        assert!(acc.token_count() > 100);
        assert_eq!(acc.dimensions(), VOCAB_NATIVE_DIMENSIONS);
    }

    #[test]
    fn known_tokens_stable_bits() {
        let emb = VocabAccumulateEmbedder::new(256).unwrap();
        let a = emb.embed_binary("checkout order cart process").unwrap();
        let b = emb.embed_binary("checkout order cart process").unwrap();
        assert_eq!(a, b);
        assert_eq!(a.len(), 32);
    }

    #[test]
    fn unknown_tokens_zero_vector() {
        let acc = TokenSpaceAccumulator::global().unwrap();
        let mut tokens = HashSet::new();
        tokens.insert("zzzxqnotinvocab999".into());
        let dense = acc.accumulate_tokens(&tokens);
        assert!(dense.iter().all(|&x| x == 0.0));
        // Sign-quantization treats 0.0 as non-negative → all bits set.
        let bits = quantize_binary(&dense);
        assert_eq!(bits, quantize_binary(&vec![0.0f32; dense.len()]));
        assert!(bits.iter().all(|&b| b == 0xff));
    }

    #[test]
    fn corrupt_matrix_rejected() {
        let err = TokenSpaceAccumulator::from_bytes(b"XXXX").unwrap_err();
        assert!(err.to_string().contains("magic") || err.to_string().contains("truncated"));
    }

    #[test]
    fn dim_packing_resize() {
        let emb = VocabAccumulateEmbedder::new(64).unwrap();
        let floats = emb.embed("checkout order").unwrap();
        assert_eq!(floats.len(), 64);
        assert_eq!(emb.embed_binary("checkout order").unwrap().len(), 8);
    }
}
