[package]
name = "rbuilder-lang-rust"
version = "0.4.2"
edition.workspace = true
rust-version.workspace = true
description = "rBuilder language plugin: rust"
license = "MIT OR Apache-2.0"

[dependencies]
rbuilder-plugin-api = { workspace = true }
rbuilder-registry = { workspace = true }
rbuilder-plugin-helpers = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-rust = "0.24"
serde_json = "1"
